//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEngine;
using System.Collections;
using System.Collections.Generic;
namespace PosterGen
{
	[System.Serializable]
	public class Options
	{
		public float area = 1.0f;
		public float offset = 0.1f;
		public float rise = 1.5f;  
		public float maxdim = 1.2f;
		public float scalemaps = 1.0f;
		public float border = 0.025f;

		public bool isCollection = false;

		public bool usemax = true;
		public bool overlap = false;
		public bool xy=true,yz=false,xz=false;
	
		public List<string> pathsToUse;
		public List<Texture2D> texturesToUse;
		public List<string> textureNames;
		
		public Shader ShaderToUse;
	}
}
